version: '3'

services:
  comby-server:
    scale: 3
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /home/app
    restart: unless-stopped
    expose:
      - "3000"
    command: ./comby-server
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - comby-server
    ports:
      - "3333:3333"